name: Playwright Tests
on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: playwright-tests:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests in Docker
        run: |
          docker run --rm \
            --ipc=host \
            -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
            -v ${{ github.workspace }}/test-results:/app/test-results \
            playwright-tests:latest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30